let fifi = "faysal";
console.log(fifi);
console.log(fifi[4]);
console.log(fifi.toUpperCase());

let a = "elzero web school";
// console.log(a.lastIndexOf("web"));
// console.log(a.indexOf("o"));
// console.log(a.slice(-9, -3));
// console.log(a.split(""));
// console.log(a.substring(2, 6));
// console.log(a.substring(6, 2));
// console.log(a.substring(-10, 6));
// console.log(a.substring(a.length - 5));
console.log(a.substring());
console.log(a.substring(0, 6));
console.log(a.substring(17));
console.log(a.includes("web"));
console.log(a.includes("web", 8));
console.log(a.startsWith("e"));
console.log(a.startsWith("w", 7));
console.log(a.endsWith("r", 5));
